language: crystal
crystal:
  - latest
  - nightly

install:
  - shards install
  - shards build

before_script:
  - bin/ameba
  - crystal tool format --check

script:
  # Run specs on their own to isolate scope of each spec.
  - crystal spec spec/athena_spec.cr --warnings all --error-on-warnings
  - crystal spec spec/cli --warnings all --error-on-warnings
  - crystal spec spec/config --warnings all --error-on-warnings
  - crystal spec spec/dependency_injection --warnings all --error-on-warnings
  - crystal spec spec/routing --warnings all --error-on-warnings

after_success:
  - crystal docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    condition: "$TRAVIS_EVENT_TYPE != cron"
